### ISSUE TITLE
readme sample and api do not match

### ISSUE THREAD

**Issue by ErKatz** [kernel1983/tornado_s3#1]
From the doc/readme:

```
apns.gateway_server.send_notification(token_hex, payload, success)
```

from the code:
 def send_notification(self, identifier, expiry, token_hex, payload, callback):
        self.write(self._get_notification(identifier, expiry, token_hex, payload), callback)

The first first 2 arguments the code expects are not in synch with the readme.

Cordially, 
 Erez

**Comment by kernel1983** [comment]
this is tornado_s3 project, not tornado_apns
